nobodyhere/config/routes.rb
Nobodyhere::Application.routes.draw do
  resources :news do
    collection do
      get 'jump'
    end
  end

  resources :codeinterviews do
    collection do
      get 'zan'
    end
  end

  resources :information

  root :to => 'news#index'

end

nobodyhere/app/models/codeinterview.rb
class Codeinterview
  include MongoMapper::Document

  key :company, String
  key :content, String
  key :created_at, Time
  key :zan_number, Integer

end

nobodyhere/app/models/information.rb
class Information
  include MongoMapper::Document

  key :company, String
  key :type, String
  key :created_at, Time
  key :salary, Integer
  key :comment, String

end

nobodyhere/app/models/new.rb
class New
  include MongoMapper::Document

  key :title, String
  key :web_urls, String
  key :created_at, Time
  key :view_number, Integer

end

nobodyhere/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

nobodyhere/app/controllers/codeinterviews_controller.rb
class CodeinterviewsController < ApplicationController
  # GET /codeinterviews
  # GET /codeinterviews.json
  def index
    @order = params[:order]?params[:order]:(session[:order]?session[:order]:"created_at")
    session[:order] = @order
    @codeinterviews = Codeinterview.order(@order + ' DESC').all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @codeinterviews }
    end
  end

  # GET /codeinterviews/1
  # GET /codeinterviews/1.json
  def show
    @codeinterview = Codeinterview.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @codeinterview }
    end
  end
  
  # GET /codeinterviews/zan/1
  # GET /codeinterviews/zan/1.json
  def zan
    @codeinterview = Codeinterview.find(params[:id])
    @codeinterview.zan_number = @codeinterview.zan_number ? (@codeinterview.zan_number + 1) : 1
    @codeinterview.save
    redirect_to codeinterviews_url, notice: "Zan successfully"
  end

  # GET /codeinterviews/new
  # GET /codeinterviews/new.json
  def new
    @codeinterview = Codeinterview.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @codeinterview }
    end
  end
  


  # POST /codeinterviews
  # POST /codeinterviews.json
  def create
    @codeinterview = Codeinterview.new(params[:codeinterview])
    @codeinterview .created_at = Time.now
    respond_to do |format|
      if @codeinterview.save
        format.html { redirect_to @codeinterview, notice: 'Codeinterview was successfully created.' }
        format.json { render json: @codeinterview, status: :created, location: @codeinterview }
      else
        format.html { render action: "new" }
        format.json { render json: @codeinterview.errors, status: :unprocessable_entity }
      end
    end
  end


end

nobodyhere/app/controllers/information_controller.rb
class InformationController < ApplicationController
  # GET /information
  # GET /information.json
  def index
    @information = Information.order('created_at DESC').all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @information }
    end
  end

  # GET /information/1
  # GET /information/1.json
  def show
    @information = Information.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @information }
    end
  end

  # GET /information/new
  # GET /information/new.json
  def new
    @information = Information.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @information }
    end
  end



  # POST /information
  # POST /information.json
  def create
    @information = Information.new(params[:information])
    @information.created_at = Time.now
    
    respond_to do |format|
      if @information.save
        format.html { redirect_to @information, notice: 'Information was successfully created.' }
        format.json { render json: @information, status: :created, location: @information }
      else
        format.html { render action: "new" }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end
end

nobodyhere/app/controllers/news_controller.rb
class NewsController < ApplicationController
  # GET /news
  # GET /news.json
  def index
    @start = params[:start]?params[:start]:"0"
    @start = @start.to_i
    @news = New.order('created_at DESC').offset(@start).limit(50).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = New.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/new
  # GET /news/new.json
  def new
    @news = New.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1/edit
  def edit
    @news = New.find(params[:id])
  end

  # POST /news
  # POST /news.json
  def create
    @news = New.new(params[:news])

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'New was successfully created.' }
        format.json { render json: @news, status: :created, location: @news }
      else
        format.html { render action: "new" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  def jump
    @news = New.find(params[:id])
    @news.view_number = @news.view_number ? @news.view_number + 1 : 1
    @news.save
    redirect_to @news.web_urls
  end
  # PUT /news/1
  # PUT /news/1.json
  def update
    @news = New.find(params[:id])

    respond_to do |format|
      if @news.update_attributes(params[:news])
        format.html { redirect_to @news, notice: 'New was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news = New.find(params[:id])
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_url }
      format.json { head :no_content }
    end
  end
end

nobodyhere/app/helpers/application_helper.rb
module ApplicationHelper
end

nobodyhere/app/helpers/codeinterviews_helper.rb
module CodeinterviewsHelper
end

nobodyhere/app/helpers/information_helper.rb
module InformationHelper
end

nobodyhere/app/helpers/news_helper.rb
module NewsHelper
end

nobodyhere/app/views/codeinterviews/_form.html.erb
<%= form_for @codeinterview, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @codeinterview.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@codeinterview.errors.count, "error") %> prohibited this information from being saved:</h2>

      <ul>
      <% @codeinterview.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :公司 %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :面试题内容%><br>
    <%= f.text_area :content %>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                codeinterviews_path, :class => 'btn' %>
  </div>
<% end %>

nobodyhere/app/views/codeinterviews/index.html.erb
<%- model_class = Codeinterview -%>
<div class="page-header">
  <h1>面试题列表<small>（<%= link_to "按赞排序", {:controller => "codeinterviews", :action => "index", :order=> "zan_number"}  %>、
  	<%= link_to "按公司排序", {:controller => "codeinterviews", :action => "index", :order=> "company"} %>、
  	<%= link_to "按更新时间排序", {:controller => "codeinterviews", :action => "index", :order=> "created_at"} %>
  	）</small></h1>
</div>
  <%= link_to '我来分享一道面试题',
              new_codeinterview_path,
              :class => 'btn btn-primary' %>
<div style="widht:100%;height:30px"></div>
<table class="table table-bordered table-striped center-table">
  <thead>
    <tr>
      <th width="10%"></th>
      <th width="10%">公司名</th>
      <th width="55%">面试题内容</th>
      <th width="14%">创建时间</th>
      <th width="10%"></th>
    </tr>
  </thead>
  <% if notice != nil %>
  	<div class="alert alert-info" id="notice"><%= notice %></div>
  <% end %>
  <tbody>
    <% @codeinterviews.each do |codeinterview| %>
      <tr>
      	<td><%
      		if (codeinterview.created_at > 3.day.ago)
      			%><span class="label label-warning">最新</span><%
      		end
      	    %>
      	    <%
      		if (codeinterview.zan_number != nil)
      			%><span class="label label-danger">赞 <%= codeinterview.zan_number%></span><%
      		end
      	    %>
      	    </td>
        <td><%= codeinterview.company %></td>
        <td><%= codeinterview.content %></td>
        <td><%= codeinterview.created_at %></td>
        <td><%= link_to "赞", {:controller => "codeinterviews", :action => "zan", :id=> codeinterview.id}, :class => 'btn btn-mini btn-danger' %> <%= link_to '详细', codeinterview, :class => 'btn btn-mini'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

nobodyhere/app/views/codeinterviews/new.html.erb
<%- model_class = Codeinterview -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

nobodyhere/app/views/codeinterviews/show.html.erb
<%- model_class = Codeinterview -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
  <% if notice != nil %>
  	<div class="alert alert-info" id="notice"><%= notice %></div>
  <% end %>
<dl class="dl-horizontal">
	  <dt>公司</dt>
	  <dd><%= @codeinterview.company %><dd>
	
	  <dt>面试题内容<dt>
	  <dd><%= @codeinterview.content %><dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              codeinterviews_path, :class => 'btn'  %>
</div>

nobodyhere/app/views/information/_form.html.erb
<%= form_for(@information) do |f| %>
  <% if @information.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@information.errors.count, "error") %> prohibited this information from being saved:</h2>

      <ul>
      <% @information.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :公司 %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :岗位 %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :薪水（万每年） %><br />
    <%= f.number_field :salary %>
  </div>
  <div class="field">
    <%= f.label :备注 %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
  </div>
<% end %>

nobodyhere/app/views/information/index.html.erb
<h1>密信列表</h1>
<%= link_to '新密信', new_information_path, :class => 'btn btn-primary' %>
<table class="table table-bordered table-striped center-table">
  <tr>
    <th width="10%">公司</th>
    <th width="20%">职位</th>   
    <th width="10%">薪水（万每年）</th>
    <th width="25%">备注</th>
    <th width="25%">创建时间</th>
    <th width="10%"></th>
  </tr>

<% @information.each do |information| %>
  <tr>
    <td><%= information.company %></td>
    <td><%= information.type %></td>
    
    <td><%= information.salary %></td>
    <td><%= information.comment %></td>
    <td><%= information.created_at %></td>
    <td><%= link_to '详细', information, :class => 'btn btn-mini'%></td>
  </tr>
<% end %>
</table>

<br />

nobodyhere/app/views/information/new.html.erb
<h1>新密件（请保证确保信息真实）</h1>

<%= render 'form' %>

<%= link_to 'Back', information_index_path, :class=>'btn' %>

nobodyhere/app/views/information/show.html.erb
  <% if notice != nil %>
  	<div class="alert alert-info" id="notice"><%= notice %></div>
  <% end %>
<dl class="dl-horizontal">
    <dt>公司</dt>
  <dd><%= @information.company %></dd>

  <dt>职位类型:</dt>
  <dd><%= @information.type %></dd>

  <dt>薪水（万每年）:</dt>
  <dd><%= @information.salary %></dd>

  <dt>备注:</dt>
  <dd><%= @information.comment %></dd>

  <dt>创建时间:</dt>
  <dd><%= @information.created_at %></dd>
<dl>
<%= link_to 'Edit', edit_information_path(@information) %> |
<%= link_to 'Back', information_index_path %>

nobodyhere/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nobody is here | 知而不言</title>
  
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Nobody is here | 知而不言</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "求职信息", news_index_path %></li>
          <li><%= link_to "面试题", codeinterviews_path %></li>
          <li><%= link_to "Offers", information_index_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="span10"><%= yield %></div>
    <div class="span2">
      <h2>用户协议</h2>
      <blockquote><p class="text-error">如果您拒绝接受该用户协议，请立即退出这个网站。</p></blockquote>
      <ol>
		  <li>不要以任何方式转载站点中的内容</li>
		  <li>不要主动在公共网站上散播站点链接</li> 
		  <li>继续浏览和在站点中发布信息代表您已接受该用户协议</li> 
	  </ol>
	  <h2>站点自律守则</h2>
      <ol>
		  <li>不以任何方式收集用户浏览记录</li>
		  <li>不修改或删除任何用户发布内容</li>
	  </ol>
    </div>
  </div>
</div>
</body>
</html>

nobodyhere/app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :web_url %><br />
    <%= f.text_field :web_url %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.time_select :created_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

nobodyhere/app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_path %>

nobodyhere/app/views/news/index.html.erb
<h1>求职信息<small>（每小时更新，覆盖水木、北邮人和饮水思源）</small></h1>
<ul class="pager">
  <li
  <% if @news.count < 50
  	 %> class="disabled" <%
  	 end %>
  ><%= link_to "上一页" , {:controller => "news", :action => "index", :start=> @start + 50 }%></li>
  <li 
  <% if @start <= 0
  	 %> class="disabled" <%
  	 end %>
  ><%= link_to "下一页" , {:controller => "news", :action => "index", :start=> @start - 50 > 0 ? @start - 50 : 0}%></li>
</ul>
<table class="table table-bordered table-striped center-table">
  <tr>
  	<th>
    <th>标题</th>
    <th>浏览数</th>
    <th>获取时间</th>
  </tr>

<% @news.each do |news| %>
  <tr>
  	<td><%
      		if (news.created_at > 1.hour.ago)
      			%><span class="label label-danger">最新</span><%
      		elsif (news.created_at > 1.day.ago)
      			%><span class="label label-warning">今日</span><%
      		end
      	    %></td>
    <td><%= link_to news.title , {:controller => "news", :action => "jump", :id=> news.id}, :target => "_blank"%></a></td>
    <td><%= news.view_number ? news.view_number : 0 %></td>
    <td><%= news.created_at %></td>
  </tr>
<% end %>
</table>
<ul class="pager">
  <li
  <% if @news.count < 50
  	 %> class="disabled" <%
  	 end %>
  ><%= link_to "上一页" , {:controller => "news", :action => "index", :start=> @start + 50 }%></li>
  <li 
  <% if @start <= 0
  	 %> class="disabled" <%
  	 end %>
  ><%= link_to "下一页" , {:controller => "news", :action => "index", :start=> @start - 50 > 0 ? @start - 50 : 0}%></li>
</ul>
<br />

nobodyhere/app/views/news/new.html.erb
<h1>New news</h1>

<%= render 'form' %>

<%= link_to 'Back', news_path %>

nobodyhere/app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @news.title %>
</p>

<p>
  <b>Web url:</b>
  <%= @news.web_url %>
</p>

<p>
  <b>Created at:</b>
  <%= @news.created_at %>
</p>


<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_path %>